### ISSUE TITLE
Tool can't find `pubspec.yaml` files on Windows machines

### ISSUE THREAD

**Issue by halildurmus** [sigurdm/pub_workspace_tool#1]
I attempted to use this tool on my [mono-repo project](https://github.com/dart-windows/dartwinrt), but it couldn't locate the `pubspec.yaml` files within the project.

The root cause of the issue appears to be this line:

https://github.com/sigurdm/pub_workspace_tool/blob/d7e54e16baff078e65f9192806e322f5776cc4eb/bin/create_workspace_pubspec.dart#L21

Since Windows uses `\` as the path separator, the `/` character should be changed with [Platform.pathSeparator](https://api.dart.dev/stable/3.0.0/dart-io/Platform/pathSeparator.html) to ensure compatibility across different platforms.

**Comment by sigurdm** [comment]
Ah - good catch.

Try again - should be fixed now

**Comment by halildurmus** [comment]
Yeah, it's fixed. Thank you.

The tool generated this `pubspec.yaml` in the project root:
```yaml
name: global_project
environment:
  sdk: ^3.3.0-71.0.dev

dev_dependencies:
  test: ">=1.24.6 <2.0.0"
  win32_registry: "^1.1.1"

dependency_overrides:
  windows_ai: {path: "packages\windows_ai"}
  windows_applicationmodel: {path: "packages\windows_applicationmodel"}
  windows_data: {path: "packages\windows_data"}
  windows_devices: {path: "packages\windows_devices"}
  windows_foundation: {path: "packages\windows_foundation"}
  windows_gaming: {path: "packages\windows_gaming"}
  windows_globalization: {path: "packages\windows_globalization"}
  windows_graphics: {path: "packages\windows_graphics"}
  windows_management: {path: "packages\windows_management"}
  windows_media: {path: "packages\windows_media"}
  windows_networking: {path: "packages\windows_networking"}
  windows_perception: {path: "packages\windows_perception"}
  windows_security: {path: "packages\windows_security"}
  windows_services: {path: "packages\windows_services"}
  windows_storage: {path: "packages\windows_storage"}
  windows_system: {path: "packages\windows_system"}
  windows_ui: {path: "packages\windows_ui"}
  windows_web: {path: "packages\windows_web"}
  winrtgen: {path: "packages\winrtgen"}
```

I guess this means my project supports shared resolution, right?

**Comment by sigurdm** [comment]
If `dart pub get` succeeds in the same folder, after the pubspec.yaml has been created, then it should mean that.

Btw. is it true that `test` and `win32_registry` are your only dev-dependencies across all those projects?

**Comment by halildurmus** [comment]
> If `dart pub get` succeeds in the same folder, after the pubspec.yaml has been created, then it should mean that.

The `dart pub get` succeeded, thanks.

FYI, I had encountered `Invalid escape sequence \w` errors in the generated pubspec.yaml file, so I had to escape the backslash `\` characters in the dependency paths:
![image](https://github.com/sigurdm/pub_workspace_tool/assets/45524029/15d6cff8-7b20-4883-816e-ac6d7145c712)

> Btw. is it true that `test` and `win32_registry` are your only dev-dependencies across all those projects?

Yes, that's correct. However, I just realized that I didn't actually need the dev dependency for `win32_registry` in one of my packages. So, as it stands, `test` is the only development dependency across all of my packages.

**Comment by sigurdm** [comment]
Ah, yet another windows bug - sorry. Should be fixed now - could you delete the pubspec.yaml and try again?

**Comment by halildurmus** [comment]
Yep, it's fixed. Thanls!

```yaml
name: global_project
environment:
  sdk: ^3.3.0-71.0.dev

dev_dependencies:
  test: ">=1.24.6 <2.0.0"

dependency_overrides:
  windows_ai: {path: "packages\\windows_ai"}
  windows_applicationmodel: {path: "packages\\windows_applicationmodel"}
  windows_data: {path: "packages\\windows_data"}
  windows_devices: {path: "packages\\windows_devices"}
  windows_foundation: {path: "packages\\windows_foundation"}
  windows_gaming: {path: "packages\\windows_gaming"}
  windows_globalization: {path: "packages\\windows_globalization"}
  windows_graphics: {path: "packages\\windows_graphics"}
  windows_management: {path: "packages\\windows_management"}
  windows_media: {path: "packages\\windows_media"}
  windows_networking: {path: "packages\\windows_networking"}
  windows_perception: {path: "packages\\windows_perception"}
  windows_security: {path: "packages\\windows_security"}
  windows_services: {path: "packages\\windows_services"}
  windows_storage: {path: "packages\\windows_storage"}
  windows_system: {path: "packages\\windows_system"}
  windows_ui: {path: "packages\\windows_ui"}
  windows_web: {path: "packages\\windows_web"}
  winrtgen: {path: "packages\\winrtgen"}
```
